### ISSUE TITLE
Null при передачи параметров методу

### ISSUE THREAD

**Issue by Feruno** [Feruno/Java2.4.BDDCucumber#1]
# Описание
Null при передачи параметров методу setInfoTransactionSecondCardForCucumber

# Локация дефекта

https://github.com/Feruno/Java2.4.BDDCucumber/blob/50c85f5fa2ee2c19583a5fbf8e491267a0493e60/src/test/java/ru/netology/page/TransactionPage.java#L19

https://github.com/Feruno/Java2.4.BDDCucumber/blob/50c85f5fa2ee2c19583a5fbf8e491267a0493e60/src/test/java/ru/netology/steps/Steps.java#L53

# Шаги воспроизведения 
1. Запустить app-ibank-build-for-testers.jar.
1. Запустить тест [(код теста)](https://github.com/Feruno/Java2.4.BDDCucumber/blob/main/src/test/resources/features/Auth.feature) вызывающий метод setInfoTransactionSecondCardForCucumber

*Ожидаемый результат :* Пройденный тест
*Фактический результат :*  Падение теста на 6 шаге
# Тест
https://github.com/Feruno/Java2.4.BDDCucumber/blob/main/src/test/resources/features/Auth.feature

# Скриншот 
Скриншот №1
![image](https://github.com/Feruno/Java2.4.BDDCucumber/assets/60847105/6dcf7039-f9de-4b2e-9961-a9b9a70a26be)
Скриншот №2
![image](https://github.com/Feruno/Java2.4.BDDCucumber/assets/60847105/2f1aec54-3e37-4bac-8e1a-a814cfc135fa)

# Окружение
* **Операционная система:** Windows 10 Pro 21H2
* **IDE:** IntelliJ IDEA Community Edition 2022.2.3
* **Java:** OpenJDK 11

**Comment by andrew-pahomov** [comment]
Переменная transactionPage не инициилизирована на момент попытки её использования, вполне ожидаемо получаете NPE. В неё необходимо положить пейдж объект до вызова его методов.
